#!/bin/bash
red='\e[1;31m'
green='\e[1;32m'
blue='\e[1;34m'
purple='\e[1;35m'
cyan='\e[1;36m'
white='\e[1;37m'
yellow='\e[1;33m'
echo -e $green '==============================================================================='
echo ""
echo -e $purple '
echo -e $purple '
$$$$$$$$\  $$$$$$\   $$$$$$\  $$\        $$$$$$\          $$\   $$\ $$\   $$\         
\__$$  __|$$  __$$\ $$  __$$\ $$ |      $$  __$$\         $$ |  $$ |$$ | $$  |        
   $$ |   $$ /  $$ |$$ /  $$ |$$ |      $$ /  \__|        $$ |  $$ |$$ |$$  /         
   $$ |   $$ |  $$ |$$ |  $$ |$$ |      \$$$$$$\  $$$$$$\ $$$$$$$$ |$$$$$  /  $$$$$$\ 
   $$ |   $$ |  $$ |$$ |  $$ |$$ |       \____$$\ \______|$$  __$$ |$$  $$<   \______|
   $$ |   $$ |  $$ |$$ |  $$ |$$ |      $$\   $$ |        $$ |  $$ |$$ |\$$\          
   $$ |    $$$$$$  | $$$$$$  |$$$$$$$$\ \$$$$$$  |        $$ |  $$ |$$ | \$$\         
   \__|    \______/  \______/ \________| \______/         \__|  \__|\__|  \__|        
                                                                                      
                                                                                      
                                                                                      

echo -e $purple '   
echo -e $green  '   
echo -e $green  '   
echo -e $green  '   
echo -e $white  "CopyRights : Devloper : Alrees info https://github.com/AL1R11/mr"
echo ""
echo -e $white  "web : https://abedst.wuiltsite.com/"
echo ""
echo -e $white  "Youtube : https://youtube.com/@captainabod4154"
echo ""
echo -e $green  '=============================================================================='
